stages:
  - build
  - deploy
  
variables:
  DOCKER_IMAGE_NAME: ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA}
  DOCKER_IMAGE_REPOSITORY: ${CI_REGISTRY_IMAGE}
  DOCKER_IMAGE_TAG: ${CI_COMMIT_SHA}
  CACHE_REPO: ${CI_REGISTRY_IMAGE}/cache
  HELM_EXPERIMENTAL_OCI: 1
  DEPLOY_DOMAIN: sept
  DEPLOY_NAME: sept-wiki
  DEPLOY_CHART_NAME: common
  DEPLOY_CHART_REGISTRY: docker.vmatrix.org.cn/matrix/infrastructure/charts
  DEPLOY_CHART_TAG: latest
  DEPLOY_CHART_URL: ${DEPLOY_CHART_REGISTRY}/${DEPLOY_CHART_NAME}:${DEPLOY_CHART_TAG}

build:
  stage: build
  image:
    name: gcr.vmatrix.org.cn/kaniko-project/executor:debug-v1.2.0
    entrypoint: [""]
  only:
    - main
  script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --registry-mirror=dockerhub.vmatrix.org.cn --context=$CI_PROJECT_DIR --dockerfile=$CI_PROJECT_DIR/Dockerfile --cache=true --destination=$DOCKER_IMAGE_NAME
  tags: ["kubernetes"]

deploy:
  stage: deploy
  image: dtzar/helm-kubectl
  tags: ["kubernetes"]
  only:
    - main
  script:
    - sh k8s/deploy.sh
  environment:
    name: production
    url: https://sept.vmatrix.org.cn
    kubernetes:
      namespace: sept-wiki
